# Generated by Django 5.2.1 on 2025-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_successful_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='psn_profile_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sync_error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='psn_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
