# Generated by Django 5.2.1 on 2025-06-03 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSNSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Trophy Sync'), ('incremental', 'Incremental Update'), ('profile', 'Profile Update'), ('manual', 'Manual Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='started', max_length=20)),
                ('games_processed', models.IntegerField(default=0)),
                ('trophies_updated', models.IntegerField(default=0)),
                ('new_trophies_earned', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('sync_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSN Sync Log',
                'verbose_name_plural': 'PSN Sync Logs',
                'db_table': 'psn_integration_psnsynclog',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PSNToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_access_token', models.TextField()),
                ('encrypted_refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField()),
                ('psn_account_id', models.CharField(max_length=100, unique=True)),
                ('psn_online_id', models.CharField(max_length=50)),
                ('psn_avatar_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psn_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSN Token',
                'verbose_name_plural': 'PSN Tokens',
                'db_table': 'psn_integration_psntoken',
            },
        ),
    ]
