# Generated by Django 5.2.1 on 2025-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psn_integration', '0002_psnapicall_psngamedifficultyhint_psnratelimit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psnsyncjob',
            name='api_calls_made',
        ),
        migrations.AddField(
            model_name='psnapicall',
            name='psnawp_method',
            field=models.CharField(blank=True, help_text='PSNAWP method called', max_length=100),
        ),
        migrations.AddField(
            model_name='psnapicall',
            name='psnawp_version',
            field=models.CharField(blank=True, help_text='PSNAWP version used', max_length=20),
        ),
        migrations.AddField(
            model_name='psngamedifficultyhint',
            name='psnawp_completion_rate',
            field=models.FloatField(blank=True, help_text='Completion rate calculated from PSNAWP user data', null=True),
        ),
        migrations.AddField(
            model_name='psngamedifficultyhint',
            name='psnawp_user_count',
            field=models.IntegerField(default=0, help_text="Number of users we've seen play this game via PSNAWP"),
        ),
        migrations.AddField(
            model_name='psnratelimit',
            name='psnawp_calls',
            field=models.IntegerField(default=0, help_text='Number of PSNAWP calls in this window'),
        ),
        migrations.AddField(
            model_name='psnratelimit',
            name='psnawp_errors',
            field=models.IntegerField(default=0, help_text='Number of PSNAWP errors in this window'),
        ),
        migrations.AddField(
            model_name='psnsyncjob',
            name='psnawp_calls_made',
            field=models.IntegerField(default=0, help_text='Number of PSNAWP API calls made during sync'),
        ),
        migrations.AddField(
            model_name='psnsyncjob',
            name='psnawp_errors',
            field=models.JSONField(blank=True, default=list, help_text='PSNAWP specific errors encountered'),
        ),
        migrations.AddField(
            model_name='psntoken',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error encountered with this token'),
        ),
        migrations.AddField(
            model_name='psntoken',
            name='npsso_token',
            field=models.TextField(blank=True, help_text='Copy of NPSSO token for explicit reference'),
        ),
        migrations.AddField(
            model_name='psntoken',
            name='psnawp_version',
            field=models.CharField(blank=True, help_text='Version of PSNAWP used with this token', max_length=20),
        ),
        migrations.AlterField(
            model_name='psnapicall',
            name='call_type',
            field=models.CharField(choices=[('validate_user', 'User Validation'), ('trophy_summary', 'Trophy Summary'), ('game_list', 'Game List'), ('game_trophies', 'Game Trophies'), ('user_trophies', 'User Game Trophies'), ('trophy_groups', 'Trophy Groups'), ('psnawp_profile', 'PSNAWP Profile'), ('psnawp_titles', 'PSNAWP Trophy Titles')], max_length=20),
        ),
        migrations.AlterField(
            model_name='psntoken',
            name='access_token',
            field=models.TextField(help_text='NPSSO token for PSNAWP authentication'),
        ),
        migrations.AlterField(
            model_name='psntoken',
            name='expires_at',
            field=models.DateTimeField(help_text='When this NPSSO token expires (usually ~60 days)'),
        ),
        migrations.AlterField(
            model_name='psntoken',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Not used with PSNAWP but kept for compatibility', null=True),
        ),
        migrations.AddIndex(
            model_name='psngamedifficultyhint',
            index=models.Index(fields=['np_communication_id'], name='psn_integra_np_comm_01404c_idx'),
        ),
        migrations.AddIndex(
            model_name='psngamedifficultyhint',
            index=models.Index(fields=['suggested_multiplier'], name='psn_integra_suggest_f66c62_idx'),
        ),
        migrations.AddIndex(
            model_name='psngamedifficultyhint',
            index=models.Index(fields=['confidence_score'], name='psn_integra_confide_6322b3_idx'),
        ),
    ]
