# Generated by Django 5.2.1 on 2025-06-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
    ]
