# Generated by Django 5.2.1 on 2025-06-04 13:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_fix_last_synced_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamedifficultyrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gamedifficultyrating',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamedifficultyrating',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='community_difficulty_rating',
            new_name='average_completion_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='admin_verified',
        ),
        migrations.RemoveField(
            model_name='game',
            name='difficulty_rating_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='np_service_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='np_title_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players_count',
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty_category',
            field=models.CharField(choices=[('extremely_easy', 'Extremely Easy (1.0-1.1x)'), ('easy', 'Easy (1.2-1.5x)'), ('standard', 'Standard (1.6-2.5x)'), ('aaa_standard', 'AAA Standard (3.0x)'), ('grind_heavy', 'Grind Heavy (4.0x)'), ('challenging', 'Challenging (5.0x)'), ('souls_like', 'Souls-like (6.0x)'), ('very_difficult', 'Very Difficult (8.0x)'), ('extremely_difficult', 'Extremely Difficult (10.0x)')], default='aaa_standard', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty_multiplier',
            field=models.FloatField(default=3.0, help_text='Multiplier for skill-based scoring (1.0 = easiest, 10.0 = hardest)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_synced',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PSV', 'PlayStation Vita'), ('PSP', 'PlayStation Portable')], default='PS5', max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='platinum_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='trophy_set_version',
            field=models.CharField(default='01.00', max_length=10),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['np_communication_id'], name='games_game_np_comm_71b43c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['difficulty_multiplier'], name='games_game_difficu_d5e824_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['platform'], name='games_game_platfor_cae15f_idx'),
        ),
        migrations.DeleteModel(
            name='GameDifficultyRating',
        ),
    ]
